apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- smm.yaml
- oauth.secret.yaml
- oauth-configmap.yaml
- oauth-client.yaml
- auth-policy.yaml
- proxy/filter-oauth2.yaml
- proxy/filter-propagate-token.yaml
