apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: proxy
    spec:
      serviceAccountName: proxy
      containers:
      - name: oauth-proxy
        image: quay.io/openshift/origin-oauth-proxy:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8180
          name: public
        args:
        - --http-address=:8180
        - --provider=openshift
        - --openshift-service-account=proxy
        - --upstream=http://localhost:8080
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --cookie-secret-file=/etc/oauth/config/cookie_secret
        - --cookie-expire=23h0m0s
        - --cookie-secret=SECRET
        - --pass-access-token
        volumeMounts:
        - mountPath: /etc/tls/private
          name: proxy-tls
        - mountPath: /etc/oauth/config
          name: oauth-config
      volumes:
        - name: proxy-tls
          secret:
            secretName: proxy-tls
        - name: oauth-config
          secret:
            secretName: oauth-config-generated