apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service-account.yaml
- service.yaml
images:
- name: oauth-proxy
  newName: registry.redhat.io/openshift4/ose-oauth-proxy
  newTag: v4.8