kind: ServiceAccount
apiVersion: v1
metadata:
  name: ext-auth
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"opendatahub-odh-gateway-525eca1d5089dbdc"}}'
    # for now hardcoded our IOR created route name for odh-dashboard 